name: CI

on:
  push:
  pull_request:
env:
  RUSTFLAGS: "-Dwarnings"
permissions:
  checks: write
  contents: read
  pull-requests: write
  id-token: write
jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Run Clippy
        run: cargo clippy --all-targets --all-features
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install latest nextest release
        uses: taiki-e/install-action@nextest
      - name: Test with latest nextest release
        uses: actions-rs/cargo@v1
        with:
          command: nextest
          args: run --profile ci
      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: target/nextest/ci/junit.xml
          check_name: Unit test
  system_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install latest nextest release
        uses: taiki-e/install-action@nextest
      - name: Test with latest nextest release
        uses: actions-rs/cargo@v1
        with:
          command: cargo
          args: build --release
      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install Python dependencies
        working-directory: system_test
        run: uv sync

      - name: Run Behave tests
        working-directory: system_test
        env:
          TEST_BINARY: ../target/release/kvnode
        run: uv run behave

      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: system_test/reports/*.xml
          check_name: System Test
